include:
  - project: "waldur/waldur-pipelines"
    file: "/templates/stages.yml"
  - project: "waldur/waldur-pipelines"
    file: "/templates/release/publish.yml"

Publish latest docker image:
  script:
    - echo "$WALDUR_DOCKER_HUB_PASSWORD" | docker login -u "$WALDUR_DOCKER_HUB_USER" --password-stdin
    - cd v2/docker
    - docker build . -f Dockerfile-waldur -t opennode/$CI_PROJECT_NAME
    - docker push opennode/$CI_PROJECT_NAME:latest

Publish docker image with specific version:
  script:
    - echo "$WALDUR_DOCKER_HUB_PASSWORD" | docker login -u "$WALDUR_DOCKER_HUB_USER" --password-stdin
    - cd v2/docker
    - docker build . -f Dockerfile-waldur -t opennode/$CI_PROJECT_NAME:$COMMIT_TAG
    - docker push opennode/$CI_PROJECT_NAME:$COMMIT_TAG
